language: perl
before_install:
    - cpanm --notest DBI DBD::CSV DBIx::XHTML_Table Spreadsheet::HTML Test::Pod Test::Pod::Coverage
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
